# TALLER #3 INTELIGENCIA ARTIFICIAL
##### 6 de abril de 2021
##### Juan Esteban Puyo Cubillos
##### Laura Alejandra rocha Rincones
##### Johan Santiago Gómez Guillen


#### 1. Crear una API que permita crear las estructuras de datos requeridas para la solución de problemas de búsqueda no-informada e informada.


La API con el nombre Busquedas_API.py que contiene las clases que permitiran construir las estructuras de datos basicas como lo son Arboles de orden N con estados y pesos de transición, grafos no dirigidos para solucionar porblemas de busqueda no informada e informada.
 
- Arboles de orden N con estados y pesos de transición
- Grafos no dirigidos 

    
**Método de la solución**
 Se creo un archivo que consta de código Python en donde se definieron funciones, clases y variables que permitiran la creación de estructuras de datos, la API consta de los siguientes metodos:
 * Class StateGraph : Clase para construir grafos
 * Class Tree: Clase para construir arbol sin estados
 * Class StateTree: Clase para construir arbol con estados

**Resultados**

Permitio organizar lógicamente el código Python y agruparlo en un módulo hace que el código sea más fácil de entender y usar. 

In [2]:
#Se importa el API Busquedas_API y se le pone el alias de AP para llamar sus Clase y metodos. 
import Busquedas_API as AP

#Se va a hacer uso de la Clase Tree para cargar un arbol que a su vez va hacer usu de la clase State
#Se puede observar que solo con escribir el alias AP y con un punto podemos usar las clase que estan dentro de la API
tree3 = AP.Tree ('A', AP.State(None, 0, False), [AP.Tree ('F',  AP.State('A', 0, False), [AP.Tree('E', AP.State('F', 0, False), ), AP.Tree('G', AP.State('F', 0, False)), AP.Tree ('J', AP.State('F', 0, False), [AP.Tree('K', AP.State('J', 0, True)), AP.Tree('L', AP.State('J', 0, False))])]), AP.Tree('B', AP.State('A', 0, False), [AP.Tree('C', AP.State('B', 0, False)), AP.Tree('H', AP.State('B', 0, False),  [AP.Tree('M' , AP.State('H', 0, False))]), AP.Tree('N', AP.State('B', 0, False))])])
#Ahora para hacer uso de uno de los metodos dentro de la API repetimos el mismo procedimiento de hicimos con las clases
#pero estabes se llamara al metodo preorder() que imprime el arbol en pre-orden y no a una clase. 
tree3.preorder()

A 0 None False
F 0 A False
E 0 F False
G 0 F False
J 0 F False
K 0 J True
L 0 J False
B 0 A False
C 0 B False
H 0 B False
M 0 H False
N 0 B False


#### 2. Secuencia de transiciones del puzzle de 8 casillas mediante búsqueda no informada:
* Búsqueda «primero en profundidad» (DFS).
* Búsqueda en profundidad limitada (DLS).
* Búsqueda en profundidad iterada ID-DLS.
* Búsqueda en anchura


El pluzzle de 8 casillas consiste, en un tablero con 9 casillas, las cuales van enumeradas del 1 al 8 más una casilla vacía. Dicha casilla vacia, es la que, con movimientos horizontales, verticales, hacia la izquierda o derecha, debe ser desplazada e intercambiada con alguno de sus vecinos, de manera que, dada una configuración inicial se llegue a una configuración final (meta).

**Método de la solución**

- Variables: 
  * class Puzzle8_State:Clase que contine la estructura de los datos del nodo
  * already_visited: Verificar si un estado ya ha sido visitado (lista de matrices)
  * move1, move2, move3,move4:Definir las movidas del puzzle de 8 casillas
  * Puzzle8_breadthfirst:Encuentra los caminos más cortos desde un vértice de origen dado a todos los demás vértices, en términos del número de aristas en los caminos.
  * Puzzle8_LimitedDepthSearch:Expande el nodo más profundo que aún no había sido expandido, colocando sus nodos borde en una estructura LIFO, expandiendose como máximo hasta una profundidad límite.
  * Puzzle8_depthfirst:Expande el nodo más interno sin visitar, colocando sus nodos borde en una estructura FIFO. 
  * ID_DFS: Combina la búsqueda primero en profundidad con la búsqueda de profundidad limitada.
  
  
**Resultados** 
Al hacer uso de los diferentes algoritmos de busqueda no informada se  identifico mediante cual se da una secuencia solución más corta para llegar a la meta en este caso cuando la secuencia de numeros queda ordenada de 1 a 8 consecutivamente siendo las busquedas de profundidad limitada e iterada las que presentan menos estados para llegar a la solución cosa que no ocurre con el algoritmo de busqueda en anchura ya que la solución esta dada por más de 20 estados.

In [4]:
import numpy as np

class Puzzle8_State:
    def __init__(self, parent, label, positions=[], move=0):
        self.parent=parent
        self.label=label
        self.solution=np.arange(1,10).reshape(3,3)
      
        self.solution[2][2]=0
        
        if positions==[]:
            self.positions=np.arange(1,10).reshape(3,3)
            self.positions[2][2]=0
        else:
            self.positions=positions
        self.expanded_states=[] # Children
    
    def getPosition(self):  
        return self.positions
    
    def setPosition(self,positions):  
        self.positions=positions
    
    def addExpandedState(self,state):
        self.expanded_states.append(state)
        
    def is_goal(self):
        return np.array_equal(self.positions,self.solution)


In [6]:
#Comprobar si dos estados posiciones son iguales
def are_equal_states(position1, position2):
    return np.array_equal(position1, position2)
    

# Verificar si un estado ya ha sido visitado (lista de matrices)
def already_visited(state, visited_states):
    for t in visited_states:
        if are_equal_states(state, t):
            return True
    return False

#Buscar la casilla vacía
def search_empty (matrix):
    for i in range (3):
        for j in range (3):
            if matrix[i][j]==0:
                return i,j
    return -1,-1

# Definir las movidas del puzzle de 8 casillas
def move1(position, empty_i, empty_j):
    result=np.arange(1,10).reshape(3,3)
    for i in range (3):
        for j in range (3):
            result[i][j] = position[i][j]
    exchange_value=position[empty_i-1][empty_j]
    result[empty_i][empty_j]=exchange_value
    result[empty_i-1][empty_j]=0
    return result

def move2(position, empty_i, empty_j):
    result=np.arange(1,10).reshape(3,3)
    for i in range (3):
        for j in range (3):
            result[i][j] = position[i][j]
    exchange_value=position[empty_i][empty_j-1]
    result[empty_i][empty_j]=exchange_value
    result[empty_i][empty_j-1]=0
    return result
    
def move3(position, empty_i, empty_j):
    result=np.arange(1,10).reshape(3,3)
    for i in range (3):
        for j in range (3):
            result[i][j] = position[i][j]
    exchange_value=position[empty_i+1][empty_j]
    result[empty_i][empty_j]=exchange_value
    result[empty_i+1][empty_j]=0
    return result

def move4(position, empty_i, empty_j):
    result=np.arange(1,10).reshape(3,3)
    for i in range (3):
        for j in range (3):
            result[i][j] = position[i][j]
    exchange_value=position[empty_i][empty_j+1]
    result[empty_i][empty_j]=exchange_value
    result[empty_i][empty_j+1]=0
    return result

In [7]:
#Creación del puzzle adicionándole un movimiento

puzzleB=Puzzle8_State(None,0)

puzzleB.setPosition(move1(puzzleB.getPosition(),search_empty(puzzleB.getPosition())[0],search_empty(puzzleB.getPosition())[1]))
#puzzleB.setPosition(move2(puzzleB.getPosition(),search_empty(puzzleB.getPosition())[0],search_empty(puzzleB.getPosition())[1]))
#puzzleB.setPosition(move3(puzzleB.getPosition(),search_empty(puzzleB.getPosition())[0],search_empty(puzzleB.getPosition())[1]))
#puzzleB.setPosition(move4(puzzleB.getPosition(),search_empty(puzzleB.getPosition())[0],search_empty(puzzleB.getPosition())[1]))
print (puzzleB.getPosition())
puzzleB.is_goal()



[[1 2 3]
 [4 5 0]
 [7 8 6]]


False

##### Búsqueda «primero en profundidad» (DFS).

La búsqueda en profundidad (DFS por depth-first search) es un algoritmo simple para encontrar un estado solución desde un estado inicial.
Para ello es necesario la implimentación de un estructura tipo pila, que permita agregar estados recorridos tipo pre orden (mediante el método stack push).


In [9]:
#Agregar a la pila
def stack_push(new,stack):
    new_stack=[new]+stack
    return new_stack

def Puzzle8_depthfirst(initial_state):
    if initial_state is None:
        return
    visit_stack=stack_push(initial_state,[])
    #Definion de la lista que guardara los estados visitados 
    visited_states=[]
    label=1
    
    while (len(visit_stack)>0):
        
        t=visit_stack.pop(0)
        #Se agrega el estado actual a la listad de estados visitados
        visited_states.append(t.getPosition())
        #Se valida si el estado actual es igual al estado solucion
        if t.is_goal() == True:
            print("\nEl estado solución es: "+str(t.label))
            print(t.getPosition())
            return 
        else:
            #Si entra a esta parte significa que no se ha llegado a el estado solución
            print("Visité el estado "+str(t.label)+", pero no es solución")
            print(t.getPosition())
            visited_states.append(t.getPosition())  
            ########################
            ## Expandir el nodo t ##
            ########################
            
            #Se procede ha hacer la expación de estados que serán todos los pasible movimientos que puede tener la posición vacia 
            #Esta puede ser Arriba, Izquierda, Abajo y Derecha dependiendoo de el marco del juego.
            
            #Se busca la posicion que almacena el cero dentro de la matriz
            empty_position=search_empty(t.getPosition())
            
            #Se valida la fila en la que se encuentra el cero y se pregunta si es una de las filas debajo de la primera
            if(empty_position[0]>0):
                new_pos_u=move1(t.getPosition(),empty_position[0],empty_position[1])
                if already_visited(new_pos_u,visited_states)==False:
                    visited_states.append(new_pos_u)                    
                    t.addExpandedState(Puzzle8_State(t,label,new_pos_u))
                    label=label+1
                    
            #Se valida la columna en la que se encuentra el cero y se pregunta si es una de las dos columnas de la izquierda
            if(empty_position[1]>0):
                new_pos_l=move2(t.getPosition(),empty_position[0],empty_position[1])
                if(already_visited(new_pos_l,visited_states)==False):
                    visited_states.append(new_pos_l)
                    t.addExpandedState(Puzzle8_State(t,label,new_pos_l))
                    label=label+1
                    
            #Se valida la fila en la que se encuentra el cero y se pregunta si es una de las filas arriba de la ultima
            if(empty_position[0]<2):
                new_pos_d=move3(t.getPosition(),empty_position[0],empty_position[1])
                if(already_visited(new_pos_d,visited_states)==False):
                    visited_states.append(new_pos_d)
                    t.addExpandedState(Puzzle8_State(t,label,new_pos_d))
                    label=label+1
            
            #Se valida la columna en la que se encuentra el cero y se pregunta si es una de las dos columnas de la derecha
            if(empty_position[1]<2):
                new_pos_r=move4(t.getPosition(),empty_position[0],empty_position[1])
                if(already_visited(new_pos_r,visited_states)==False):
                    visited_states.append(new_pos_r)
                    t.addExpandedState(Puzzle8_State(t,label,new_pos_r))
                    label=label+1
            #Se pregunta si la lista de estados expandidos tiene un elemento o esvacia
            if t.expanded_states is not None:
                for child in t.expanded_states:
                    visit_stack=stack_push(child,visit_stack)
    return "failure"

In [10]:
Puzzle8_depthfirst(puzzleB)

Visité el estado 0, pero no es solución
[[1 2 3]
 [4 5 0]
 [7 8 6]]

El estado solución es: 3
[[1 2 3]
 [4 5 6]
 [7 8 0]]


<ipython-input-4-8aa98376089c>:11: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if positions==[]:


##### Búsqueda en profundidad limitada (DLS).

Es una modificación del algoritmo de búsqueda en profunidad (DLS) que trata de limitar el avance del algoritmo por ramas que no conducen a un estado solución. Para ello, como parámetro adicional estará limit. Para la exploración de los hijos del árbol se implementará un método recursivo, concluyendo en la evaluación para determinar si hay error de corte o se encontró la solución.

In [13]:
#Estado inicial (root) y límite agregado
def Puzzle8_LimitedDepthSearch(root,limit):
    if root is None:
        return "fallo"
    
    #Es necesario agregar 2 variables globales para validar el fin del recorrido (por error de corte y esta solución)
    global success_state
    global end_recursion # Necesario para superar la limitación de Python de no implementar "tail-call elimination"
    end_recursion=False
    
    visited_states=[]
    array=[]
    label=1
    
    result=DFS_recursion(root,limit,visited_states,label,array)
    if result=="success":
        print("El estado solución es " ,success_state.label )
        
        print(success_state.getPosition())
        
    return result

 


#Función recursiva, para cada ejecución valida si hay error de corte
#Estado solución o fallo.
def DFS_recursion(t, limit,visited_states,label,array):
    global end_recursion
    if end_recursion == True:
        return "success"
    elif t is None:
        return "fallo"
    elif limit == 0:
        print (t.label, "error de corte")
        return "error_corte"
    global success_state
    if(t.is_goal()):
        print("Encontré una solución en el nodo: ",t.label)
        success_state=t
        end_recursion = True
        return "success"
    else:
        
        print("Visité el estado "+str(t.label)+", pero no es solución")
        print(t.getPosition())
        

           
        
        visited_states.append(t.getPosition())  
        ocurrio_corte=False;
        ########################
        ## Expandir el nodo t ##
        ########################
        
        
        #Identifica la posición del 0 para empezar a realizar movimientos
        empty_position=search_empty(t.getPosition())
        
        print("el 0 esta en la fila" ,empty_position[0]+1, "y en la columna",empty_position[1]+1)
        flag = 0
        
        
        #La implemetación de expansión de nodos no cambia
        if(empty_position[0]>0):
            new_pos_u=move1(t.getPosition(),empty_position[0],empty_position[1]) 
            if (already_visited(new_pos_u,visited_states)==False):
                print("arriba")
                visited_states.append(new_pos_u)                    
                t.addExpandedState(Puzzle8_State(t,label,new_pos_u))
                
                
                flag = flag + 1
                label=label+1
        if(empty_position[1]>0):
            
            new_pos_l=move2(t.getPosition(),empty_position[0],empty_position[1])
            if(already_visited(new_pos_l,visited_states)==False):
                print("izquierda")
                visited_states.append(new_pos_l)
                t.addExpandedState(Puzzle8_State(t,label,new_pos_l))
                
                flag = flag + 1
                label=label+1
        if(empty_position[0]<2):
            new_pos_d=move3(t.getPosition(),empty_position[0],empty_position[1])
            if(already_visited(new_pos_d,visited_states)==False):
                print("abajo")
                visited_states.append(new_pos_d)
                t.addExpandedState(Puzzle8_State(t,label,new_pos_d))
                
                flag = flag + 1
                label=label+1
                
        if(empty_position[1]<2):
            new_pos_r=move4(t.getPosition(),empty_position[0],empty_position[1])
            if(already_visited(new_pos_r,visited_states)==False):
                print("derecha")
                visited_states.append(new_pos_r)
                t.addExpandedState(Puzzle8_State(t,label,new_pos_r))
                
                flag = flag + 1
                label=label+1

        
        #Bandera para analizar cuantos hijos se crearon en la expansión del nodo
        print("cree", flag, "hijos")
        
        
        flag2 = 0
        
        if t.expanded_states is not None:
            
            
            for child in t.expanded_states:
                
                
                
                array.append(child.label)
                
                
                if len(array)==len(set(array)):
                    #if (already_visited(child.getPosition(),visited_states)==True):
                        #print(child.label)
                        #if (child.label in array):
                            #print(array)
                    
                    
                    if (flag2 != flag):
                        
                        flag2 = flag2 + 1
                        print("Padre: ", t.label, "Hijo explorado: ",child.label)
                        result=DFS_recursion(child, limit-1,visited_states,label,array)
                    
                    
                        #Validación de error de corte
                        if result == "error_corte":
                            ocurrio_corte=True
                        
                
                else:
                    print("Padre: ", t.label, "Hijo explorado: ",child.label)
                    result=DFS_recursion(child, limit-1,visited_states,label,array)
                    
                    if result == "error_corte":
                        ocurrio_corte=True
                    
                
                            
                            
        if end_recursion:
            return "success"
        else:
            return "seguir"

In [19]:

#EJEMPLO PARA PROBAR EL MÉTODO DE BÚSQUEDA
puzzleB=Puzzle8_State(None,0)

puzzleB.setPosition(move1(puzzleB.getPosition(),search_empty(puzzleB.getPosition())[0],search_empty(puzzleB.getPosition())[1]))
print (puzzleB.getPosition())
puzzleB.is_goal()


[[1 2 3]
 [4 5 0]
 [7 8 6]]


False

In [18]:
Puzzle8_LimitedDepthSearch(puzzleB,3)

Visité el estado 0, pero no es solución
[[1 2 3]
 [4 5 0]
 [7 8 6]]
el 0 esta en la fila 2 y en la columna 3
arriba
izquierda
abajo
cree 3 hijos
Padre:  0 Hijo explorado:  1
Visité el estado 1, pero no es solución
[[1 2 0]
 [4 5 3]
 [7 8 6]]
el 0 esta en la fila 1 y en la columna 3
izquierda
cree 1 hijos
Padre:  1 Hijo explorado:  4
Visité el estado 4, pero no es solución
[[1 0 2]
 [4 5 3]
 [7 8 6]]
el 0 esta en la fila 1 y en la columna 2
izquierda
abajo
cree 2 hijos
Padre:  4 Hijo explorado:  5
5 error de corte
Padre:  4 Hijo explorado:  6
6 error de corte
Padre:  0 Hijo explorado:  2
Visité el estado 2, pero no es solución
[[1 2 3]
 [4 0 5]
 [7 8 6]]
el 0 esta en la fila 2 y en la columna 2
arriba
izquierda
abajo
cree 3 hijos
Padre:  2 Hijo explorado:  4
Visité el estado 4, pero no es solución
[[1 0 3]
 [4 2 5]
 [7 8 6]]
el 0 esta en la fila 1 y en la columna 2
izquierda
derecha
cree 2 hijos
Padre:  4 Hijo explorado:  7
7 error de corte
Padre:  4 Hijo explorado:  8
8 error de corte


<ipython-input-4-8aa98376089c>:11: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if positions==[]:


'success'

##### Búsqueda en profundidad iterada ID-DLS.

El método encuentra el mejor límite de profundidad y lo
hace aumentando gradualmente el límite hasta encontrar una meta.
Este algoritmo realiza una búsqueda en profundidad hasta un cierto
"límite de profundidad", y sigue aumentando el límite después de
cada iteración hasta que se encuentra el estado objetivo. El aumento es controlado a través de la variable max_level

**Nota**: Confución el proceso de etiquetado (label) para cada hijo: Debido a factores en estudio, el etiquetado implementado en ID_DFS agrega dos estados con la misma etiqueta pero con diferentes atributos, dando la impresión de que se están visitando estados repetidos.

In [24]:
def ID_DFS(t, max_level):
    
    #Aumenta gradualmente con cada iteración dentro de max_level
    for limit_level in range(max_level):
        
        #Implementación de la búsqueda limitada
        result=Puzzle8_LimitedDepthSearch(t,limit_level)
        print("El resultado para esta iteración es: ",result)
        if result=="fallo": 
            print("No se pudo encontrar una respuesta")
            return "fallo"
        elif result=="success":
            return result
        
    if result=="error_corte":
        print("No se pudo encontrar una respuesta hasta el nivel ", max_level)
        result="fallo_corte"
    return result


In [21]:
ID_DFS(puzzleB,3)

0 error de corte
El resultado para esta iteración es:  error_corte
Visité el estado 0, pero no es solución
[[1 2 3]
 [4 5 0]
 [7 8 6]]
el 0 esta en la fila 2 y en la columna 3
arriba
izquierda
abajo
cree 3 hijos
Padre:  0 Hijo explorado:  1
1 error de corte
Padre:  0 Hijo explorado:  2
2 error de corte
Padre:  0 Hijo explorado:  3
3 error de corte
El resultado para esta iteración es:  seguir
Visité el estado 0, pero no es solución
[[1 2 3]
 [4 5 0]
 [7 8 6]]
el 0 esta en la fila 2 y en la columna 3
arriba
izquierda
abajo
cree 3 hijos
Padre:  0 Hijo explorado:  1
Visité el estado 1, pero no es solución
[[1 2 0]
 [4 5 3]
 [7 8 6]]
el 0 esta en la fila 1 y en la columna 3
izquierda
cree 1 hijos
Padre:  1 Hijo explorado:  4
4 error de corte
Padre:  0 Hijo explorado:  2
Visité el estado 2, pero no es solución
[[1 2 3]
 [4 0 5]
 [7 8 6]]
el 0 esta en la fila 2 y en la columna 2
arriba
izquierda
abajo
cree 3 hijos
Padre:  2 Hijo explorado:  4
4 error de corte
Padre:  2 Hijo explorado:  5
5 er

<ipython-input-4-8aa98376089c>:11: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if positions==[]:


'success'

#### Búsqueda en anchura

Al diferencia del algoritmo de búsqueda en profundidad, se implementa una estructutura cola FIFO. De igual manera evaluan la existencia de estados repetidos.

In [26]:
def Puzzle8_breadthfirst(initial_state):
    if initial_state is None:
        return
    
    #FIFO
    visit_queue=[]
    visit_queue.append(initial_state)
    #Creación de lista para validar estados repetidos
    visited_states=[]
    
    label=1
    while (len(visit_queue)>0):
        
        #Encolar el primer elemento
        t=visit_queue.pop(0) 
        
        visited_states.append(t.getPosition())
        
        if t.is_goal() == True:
            print("\nEl estado solución es: "+str(t.label))
            print(t.getPosition())
            return 
        else:
            print("Visité el estado "+str(t.label)+", pero no es solución")
            print(t.getPosition())
            ########################
            ## Expandir el nodo t ##
            ########################
            empty_position=search_empty(t.getPosition())
            if(empty_position[0]>0):
                new_pos_u=move1(t.getPosition(),empty_position[0],empty_position[1])
                if already_visited(new_pos_u,visited_states)==False:
                    visited_states.append(new_pos_u)                    
                    t.addExpandedState(Puzzle8_State(t,label,new_pos_u))
                    label=label+1
            if(empty_position[1]>0):
                new_pos_l=move2(t.getPosition(),empty_position[0],empty_position[1])
                if(already_visited(new_pos_l,visited_states)==False):
                    visited_states.append(new_pos_l)
                    t.addExpandedState(Puzzle8_State(t,label,new_pos_l))
                    label=label+1
            if(empty_position[0]<2):
                new_pos_d=move3(t.getPosition(),empty_position[0],empty_position[1])
                if(already_visited(new_pos_d,visited_states)==False):
                    visited_states.append(new_pos_d)
                    t.addExpandedState(Puzzle8_State(t,label,new_pos_d))
                    label=label+1
            if(empty_position[1]<2):
                new_pos_r=move4(t.getPosition(),empty_position[0],empty_position[1])
                if(already_visited(new_pos_r,visited_states)==False):
                    visited_states.append(new_pos_r)
                    t.addExpandedState(Puzzle8_State(t,label,new_pos_r))
                    label=label+1

            if t.expanded_states is not None:
                for child in t.expanded_states:
                    visit_queue.append(child)
    return "failure"

In [27]:
Puzzle8_breadthfirst(puzzleB)

Visité el estado 0, pero no es solución
[[1 2 3]
 [4 5 0]
 [7 8 6]]
Visité el estado 1, pero no es solución
[[1 2 0]
 [4 5 3]
 [7 8 6]]
Visité el estado 2, pero no es solución
[[1 2 3]
 [4 0 5]
 [7 8 6]]

El estado solución es: 3
[[1 2 3]
 [4 5 6]
 [7 8 0]]


<ipython-input-4-8aa98376089c>:11: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if positions==[]:


#### 3. Búsqueda de costo uniforme para encontrar la ruta
de menor coste entre Brest y:
*  Grenoble.
*  Estrasburgo.
*  Marsella.

Mediante el costo uniforme se busca encontrar la ruta de menor coste explorando los nodos en función de su costo de ruta desde Brest que es la ciudad de origen y las diferentes ciudades de destino.
La idea del algoritmo consiste en ir explorando todos los caminos más cortos que parten de la ciudad Brest y que llevan a todos los demás vértices, enumerando todos los nodos del espacio de estados por costes que se van incrementando; cuando se obtiene el camino más corto desde la ciudad de origen, a la ciudad de destino destino objetivo de la búsqueda, el algoritmo se detiene.

**Método de la solución**

- Variables: 
  * _city_info: Contiene el grafo especificado con la ciudad de origen, destino y su costo.
  * class Node: Clase que contine la estructura de los datos del nodo
  * is_node_in_frontier: Función para identificar si el nodo llega a la ciudad de destino
  * uniform_cost_search: Funcion para implementar algoritmo de costo uniforme
  * frontier_priority_replace_by_priority: inserta los nodos existentes en la cola de prioridad y se agrega directamente al final de la cola.

La búsqueda comienza en el nodo raíz en este caso la ciudad de origen, continúa visitando el siguiente nodo que tiene el menor costo total de la raíz expandiendo el nodo con el coste de la ruta total más bajo desde el nodo inicial, los nodos son visitados de esta manera hasta que se alcanza un estado objetivo.En este caso cuando llega alguna de las ciudades( Grenoble, Estrasburgo y Marselle).

**Resultados**

El algoritmo de busqueda de costo uniforme permitio conocer cual es la ruta con en el menor costo a tomar por las diferentes ciudades desde Brest hasta la ciudad de destido.

In [38]:
import pandas as pd 
from pandas import Series, DataFrame
 
# Información de la ciudad: city1 city2 path_cost
_city_info = None
 
 # FIFO ordenado de acuerdo con el consumo de ruta
_frontier_priority = []
 
# Estructura de datos del nodo
class Node:
    def __init__(self, state, parent, action, path_cost):
        self.state = state
        self.parent = parent
        self.action = action
        self.path_cost = path_cost
def main():
    global _city_info
    import_city_info()
    
    a = True
    
    while a == True:
        src_city = "Brest"
        dst_city = input('Ingrese la ciudad de destino\n')
        
        if(dst_city == "exit"):
            a = False
            break
        
        result = uniform_cost_search(src_city, dst_city)
        if not result:
            print('Desde la ciudad: %s hasta la ciudad %s busqueda fallida' % (src_city, dst_city))
        else:
            print('Desde la ciudad: %s hasta la ciudad %s busqueda completa' % (src_city, dst_city))
            path = []
            while True:
                path.append(result.state)
                if result.parent is None:
                    break
                result = result.parent
            size = len(path)
            for i in range(size):
                if i < size - 1:
                    print('%s->' % path.pop(), end='')
                else:
                    print(path.pop())
 
def import_city_info():
    global _city_info
    data = [{'city1': 'Calais', 'city2': 'Nancy', 'path_cost': 534},
            {'city1': 'Calais', 'city2': 'Paris', 'path_cost': 297},
            {'city1': 'Calais', 'city2': 'Caen', 'path_cost': 120},
            {'city1': 'Nancy', 'city2': 'Calais', 'path_cost': 534},
            {'city1': 'Paris', 'city2': 'Calais', 'path_cost': 297},
            {'city1': 'Caen', 'city2': 'Caen', 'path_cost': 120},
            {'city1': 'Paris', 'city2': 'Caen', 'path_cost': 241},
            {'city1': 'Rennes', 'city2': 'Caen', 'path_cost': 176},
            {'city1': 'Caen', 'city2': 'Calais', 'path_cost': 120},
            {'city1': 'Caen', 'city2': 'Paris', 'path_cost': 241},
            {'city1': 'Caen', 'city2': 'Rennes', 'path_cost': 176},
            {'city1': 'Rennes', 'city2': 'Brest', 'path_cost': 244},
            {'city1': 'Rennes', 'city2': 'Paris', 'path_cost': 348},
            {'city1': 'Rennes', 'city2': 'Nantes', 'path_cost': 107},
            {'city1': 'Brest', 'city2': 'Rennes', 'path_cost': 244},
            {'city1': 'Paris', 'city2': 'Rennes', 'path_cost': 348},
            {'city1': 'Nantes', 'city2': 'Rennes', 'path_cost': 107},
            {'city1': 'Paris', 'city2': 'Nancy', 'path_cost': 372},
            {'city1': 'Paris', 'city2': 'Limoges', 'path_cost': 396},
            {'city1': 'Paris', 'city2': 'Dijon', 'path_cost': 313},
            {'city1': 'Nancy', 'city2': 'Paris', 'path_cost': 372},
            {'city1': 'Limoges', 'city2': 'Paris', 'path_cost': 396},
            {'city1': 'Nancy', 'city2': 'Stcasbourg', 'path_cost': 145},
            {'city1': 'Nancy', 'city2': 'Dijon', 'path_cost': 201},
            {'city1': 'Stcasbourg', 'city2': 'Nancy', 'path_cost': 145},
            {'city1': 'Dijon', 'city2': 'Nancy', 'path_cost': 201},
            {'city1': 'Dijon', 'city2': 'Lyon', 'path_cost': 192},
            {'city1': 'Dijon', 'city2': 'Stcasbourg', 'path_cost': 335},
            {'city1': 'Dijon', 'city2': 'Paris', 'path_cost': 313},
            {'city1': 'Nancy', 'city2': 'Dijon', 'path_cost': 201},
            {'city1': 'Lyon', 'city2': 'Dijon', 'path_cost': 192},
            {'city1': 'Stcasbourg', 'city2': 'Dijon', 'path_cost': 335},
            {'city1': 'Lyon', 'city2': 'Grenoble', 'path_cost': 104},
            {'city1': 'Lyon', 'city2': 'Avignon', 'path_cost': 216},
            {'city1': 'Lyon', 'city2': 'Limoges', 'path_cost': 389},
            {'city1': 'Grenoble', 'city2': 'Lyon', 'path_cost': 104},
            {'city1': 'Avignon', 'city2': 'Lyon', 'path_cost': 216},
            {'city1': 'Limoges', 'city2': 'Lyon', 'path_cost': 389},
            {'city1': 'Grenoble', 'city2': 'Avignon', 'path_cost': 227},
            {'city1': 'Avignon', 'city2': 'Grenoble', 'path_cost': 227},
            {'city1': 'Avignon', 'city2': 'Marselle', 'path_cost': 99},
            {'city1': 'Marselle', 'city2': 'Avignon', 'path_cost': 99},
            {'city1': 'Marselle', 'city2': 'Nice', 'path_cost': 188},
            {'city1': 'Nice', 'city2': 'Marselle', 'path_cost': 188},
            {'city1': 'Avignon', 'city2': 'MontPellier', 'path_cost': 121},
            {'city1': 'MontPellier', 'city2': 'Avignon', 'path_cost': 121},
            {'city1': 'MontPellier', 'city2': 'Toulouse', 'path_cost': 240},
            {'city1': 'Toulouse', 'city2': 'MontPellier', 'path_cost': 240},
            {'city1': 'Toulouse', 'city2': 'Limoges', 'path_cost': 313},
            {'city1': 'Toulouse', 'city2': 'Bordeaux', 'path_cost': 253},
            {'city1': 'Limoges', 'city2': 'Toulouse', 'path_cost': 313},
            {'city1': 'Bordeaux', 'city2': 'Toulouse', 'path_cost': 253},
            {'city1': 'Bordeaux', 'city2': 'Limoges', 'path_cost': 220},
            {'city1': 'Bordeaux', 'city2': 'Nantes', 'path_cost': 329},
            {'city1': 'Limoges', 'city2': 'Bordeaux', 'path_cost': 220},
            {'city1': 'Nantes', 'city2': 'Bordeaux', 'path_cost': 329},
            {'city1': 'Nantes', 'city2': 'Limoge', 'path_cost': 329},
            {'city1': 'Limoge', 'city2': 'Nantes', 'path_cost': 329}]

            
    _city_info = DataFrame(data, columns=['city1', 'city2', 'path_cost'])

def is_node_in_frontier(frontier, node):
    for x in frontier:
        if node.state == x.state:
            return True
    return False
 
def uniform_cost_search(src_state, dst_state):
    global _city_info, _frontier_priority
    
    node = Node(src_state, None, None, 0)
    frontier_priority_add(node)
    explored = []
    
    while True:
        if len(_frontier_priority) == 0:
            return False
        node = _frontier_priority.pop(0)
        explored.append(node.state)
                 # Prueba de objetivo
        if node.state == dst_state:
            print('\t this node is goal!')
            return node
        if node.parent is not None:
            print('deal node:state:%s\tparent state:%s\tpath cost:%d' % (node.state, node.parent.state, node.path_cost))
        else:
            print('deal node:state:%s\tparent state:%s\tpath cost:%d' % (node.state, None, node.path_cost))
    
                 # Atravesar nodos secundarios
        for i in range(len(_city_info)):
            dst_city = ''
            if _city_info['city1'][i] == node.state:
                dst_city = _city_info['city2'][i]
            elif _city_info['city2'][i] == node.state:
                dst_city = _city_info['city1'][i]
            if dst_city == '':
                continue
            child = Node(dst_city, node, 'go', node.path_cost + _city_info['path_cost'][i])
            print('\tchild node:state:%s path cost:%d' % (child.state, child.path_cost))
            
            if child.state not in explored and not is_node_in_frontier(_frontier_priority, child):
                frontier_priority_add(child)
                print('\t\t add child to frontier')
            elif is_node_in_frontier(_frontier_priority, child):
                                 # Reemplazar con nodos con menos consumo de ruta
                frontier_priority_replace_by_priority(child)
 
def frontier_priority_add(node):
    """
        :param Node node:
        :return:
        """
    global _frontier_priority
    size = len(_frontier_priority)
    for i in range(size):
                 # Si el nodo recién agregado tiene un umbral pequeño, insértelo en la cola
        if node.path_cost < _frontier_priority[i].path_cost:
            _frontier_priority.insert(i, node)
            return
         # De lo contrario, el nodo recién agregado tiene un umbral mayor que los nodos existentes en la cola de prioridad y se agrega directamente al final de la cola
    _frontier_priority.append(node)
 
 
def frontier_priority_replace_by_priority(node):
    """
        :param Node node:
        :return:
        """
    global _frontier_priority
    size = len(_frontier_priority)
    for i in range(size):
        if _frontier_priority[i].state == node.state and _frontier_priority[i].path_cost > node.path_cost:
            print('\t\t replace state: %s old cost:%d new cost:%d' % (node.state,_frontier_priority[i].path_cost,node.path_cost))
            _frontier_priority[i] = node
            return
 
if __name__ == '__main__':
    main()

Ingrese la ciudad de destino
 Marselle


deal node:state:Brest	parent state:None	path cost:0
	child node:state:Rennes path cost:244
		 add child to frontier
	child node:state:Rennes path cost:244
deal node:state:Rennes	parent state:Brest	path cost:244
	child node:state:Caen path cost:420
		 add child to frontier
	child node:state:Caen path cost:420
	child node:state:Brest path cost:488
	child node:state:Paris path cost:592
		 add child to frontier
	child node:state:Nantes path cost:351
		 add child to frontier
	child node:state:Brest path cost:488
	child node:state:Paris path cost:592
	child node:state:Nantes path cost:351
deal node:state:Nantes	parent state:Rennes	path cost:351
	child node:state:Rennes path cost:458
	child node:state:Rennes path cost:458
	child node:state:Bordeaux path cost:680
		 add child to frontier
	child node:state:Bordeaux path cost:680
	child node:state:Limoge path cost:680
		 add child to frontier
	child node:state:Limoge path cost:680
deal node:state:Caen	parent state:Rennes	path cost:420
	child nod

Ingrese la ciudad de destino
 Grenoble


deal node:state:Brest	parent state:None	path cost:0
	child node:state:Rennes path cost:244
		 add child to frontier
	child node:state:Rennes path cost:244
deal node:state:Rennes	parent state:Brest	path cost:244
	child node:state:Caen path cost:420
		 add child to frontier
	child node:state:Caen path cost:420
	child node:state:Brest path cost:488
	child node:state:Paris path cost:592
		 add child to frontier
	child node:state:Nantes path cost:351
		 add child to frontier
	child node:state:Brest path cost:488
	child node:state:Paris path cost:592
	child node:state:Nantes path cost:351
deal node:state:Nantes	parent state:Rennes	path cost:351
	child node:state:Rennes path cost:458
	child node:state:Rennes path cost:458
	child node:state:Bordeaux path cost:680
		 add child to frontier
	child node:state:Bordeaux path cost:680
	child node:state:Limoge path cost:680
		 add child to frontier
	child node:state:Limoge path cost:680
deal node:state:Caen	parent state:Rennes	path cost:420
	child nod

Ingrese la ciudad de destino
 exit
